resources:
  - name: jenkins_argon
    type: externalCIServer
    
jobs:
  - name: stage_1
    type: runSh
    steps:
      - IN: test
      - TASK:
          script:
            - echo "This is stage_1"
